language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - android-28
    - build-tools-28.0.3
    - platform-tools
    - tools
    - extra
    - add-on
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - nvm install 10
  - node --version
  - npm i -g react-native-cli
  - mkdir -p ./android/app/src/main/assets/
  - mkdir -p ./android/app/src/main/res/
  - sh appcenter-post-clone.sh
install:
  - npm i
script:
  - npm run build:prd
before_deploy:
  - mv ./android/app/build/outputs/apk/release/app-release.apk ./mopcon.apk
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $github_token
  file: ./mopcon.apk
  on:
    tags: true