language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - build-tools-27.0.3
    - build-tools-28.0.3
    - android-23
    - android-26
    - android-27
    - android-28
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  - nvm install 10
  - node --version
  - npm i -g react-native-cli
  - mkdir -p ./android/app/src/main/assets/
  - mkdir -p ./android/app/src/main/res/
  - openssl des-cbc -d -k $MOPCON_DES_KEY -in secrets.tar.enc -out secrets.tar
  - tar xvf ./secrets.tar
  - mv release.keystore ./android/app/
  - mv google-services.json ./android/app/
install:
  - npm i
script:
  - npm run build:prd
before_deploy:
  - mv ./android/app/build/outputs/apk/release/app-release.apk ./mopcon.apk
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $github_token
  file: ./mopcon.apk
  on:
    tags: true